### ISSUE TITLE
@six.add_metaclass and Django models

### ISSUE THREAD

**Issue by benjaminp** [benjaminp/six#118]
Originally reported by: **sodas tsai (Bitbucket: [sodastsai](https://bitbucket.org/sodastsai), GitHub: [sodastsai](https://github.com/sodastsai))**

----------------------------------------

While making Django models with custom metaclass,
I used the decorator to keep compatibility between Python 2 and 3:

```python3
from django.db import models
from django.db.models.base import ModelBase
import six


class CustomModelBase(ModelBase):
    def __init__(cls, name, bases, attrs):
        super(CustomModelBase, cls).__init__(name, bases, attrs)
        print(name)


@six.add_metaclass(CustomModelBase)
class CustomModel(models.Model):
    some_field = models.CharField(max_length=128)

```

But while starting my Django server, I got following exceptions:
```py3tb
Traceback (most recent call last):
  File "<input>", line 5, in <module>
  File "/work/venv/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/work/venv/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/work/venv/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/work/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/work/core/models/__init__.py", line 88, in <module>
    class CustomModel(models.Model):
  File "/work/venv/lib/python3.4/site-packages/six.py", line 794, in wrapper
    return metaclass(cls.__name__, cls.__bases__, orig_vars)
  File "/work/venv/lib/python3.4/site-packages/django/db/models/base.py", line 168, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/work/venv/lib/python3.4/site-packages/django/db/models/base.py", line 297, in add_to_class
    value.contribute_to_class(cls, name)
  File "/work/venv/lib/python3.4/site-packages/django/db/models/options.py", line 129, in contribute_to_class
    if self.meta:
AttributeError: 'Options' object has no attribute 'meta'
```

By using Python 3's metaclass syntax, the ```CustomModel``` class works correctly without such ```AttributeError```.
```python3
from django.db import models
from django.db.models.base import ModelBase


class CustomModelBase(ModelBase):
    def __init__(cls, name, bases, attrs):
        super(CustomModelBase, cls).__init__(name, bases, attrs)
        print(name)


class CustomModel(models.Model, metaclass=CustomModelBase):
    some_field = models.CharField(max_length=128)

```

It seems the decorator forgot to copy some attributes that set by Django's ```ModelBase``` metaclass.

I'm using ```Python 3.4.2```, ```six 1.9.0```, and ```Django 1.7.4``` on ```OS X 10.10.2```.

----------------------------------------
- Bitbucket: https://bitbucket.org/gutworth/six/issue/118

**Comment by jaraco** [comment]
I believe this issue as an instance of the caveat that [benjamin highlighted here](https://bitbucket.org/gutworth/six/pull-requests/12/add-patch_with_metaclass-which-provides-a/diff#comment-490556). I'm not aware of a workaround other than to use the alternate `with_metaclass`.

**Comment by jaraco** [comment]
I was able to replicate your finding by running this script under [rwt](https://pypi.org/project/rwt):

```
__requires__ = ['django', 'six']

import django.conf
from django.db import models
from django.db.models.base import ModelBase
import six

django.conf.settings.configure(
    INSTALLED_APPS=['__main__'],
)

django.setup()

class CustomModelBase(ModelBase):
    def __init__(cls, name, bases, attrs):
        super(CustomModelBase, cls).__init__(name, bases, attrs)
        print(name)

@six.add_metaclass(CustomModelBase)
class CustomModel(models.Model):
    some_field = models.CharField(max_length=128)
    app_label = "my_app"
```

I don't yet have an explanation.

**Comment by R-Studio** [comment]
I have this problem:
```
@six.add_metaclass(abc.ABCMeta)
AttributeError: module 'six' has no attribute 'add_metaclass'
```
Is there a workaround for this bug?
_I use python 3.7.4 and six 1.12.0._

**Comment by jaraco** [comment]
@R-Studio Your problem is different from the reported issue, but honestly the problem is likely in your implementation. When you get the error, you should inspect "six" to see if it's the module from six-1.12.0. Likely you have another module in your path `six.py` that's masking the six package.
