### ISSUE TITLE
Have a fallback for sys._getframe() usage in exec_() to work in IronPython

### ISSUE THREAD

**Issue by benjaminp** [benjaminp/six#135]
Originally reported by: **Brett Cannon (Bitbucket: [brettcannon](https://bitbucket.org/brettcannon), GitHub: [brettcannon](https://github.com/brettcannon))**

----------------------------------------

It prevents IronPython from running due to its lack of sys._getframe() support. Otherwise issue #126 suggests simply dropping exec_() which obviously also solved the problem.

----------------------------------------
- Bitbucket: https://bitbucket.org/gutworth/six/issue/135

**Comment by danielschenk** [comment]
I guess I'm running into this issue when I try to install pydot with IronPython 2.7.7. The `-X:FullFrames` workaround doesn't seem to work in this case. See also: https://github.com/erocarrera/pydot/issues/148
```
➤ ipy -V
IronPython 2.7 2.7.7.0 on .NET 4.0.30319.42000
                                                                                                                                                                                                                                         ✔
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
➤ ipy -X:FullFrames -m pip install pydot
Collecting pydot
  Using cached pydot-1.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\setuptools\__init__.py", line 11, in <module>
      File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\setuptools\extern\__init__.py", line 1, in <module>
      File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pkg_resources\__init__.py", line 46, in <module>
      File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pkg_resources\extern\__init__.py", line 42, in load_module
      File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pkg_resources\_vendor\six.py", line 701, in <module>
      File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pkg_resources\_vendor\six.py", line 692, in exec_
    AttributeError: 'module' object has no attribute '_getframe'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\sd71ein\appdata\local\temp\mobaxterm7.1\tmp\pip-build-cwuvdc\pydot\
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

On IronPython 2.7.5 it works, and `-X:Frames` is sufficient in that case.
```
➤ ipy -V
IronPython 2.7 2.7.5.0 on .NET 4.0.30319.42000
                                                                                                                                                                                                                                         ✔
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
➤ ipy -X:Frames -m pip install pydot
Downloading/unpacking pydot
C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py:1: DeprecationWarning: object.__new__() takes no parameters
  # urllib3/connectionpool.py
  Downloading pydot-1.2.3.tar.gz
  Running setup.py (path:c:\users\sd71ein\appdata\local\temp\mobaxterm7.1\tmp\pip_build_sd71ein\pydot\setup.py) egg_info for package pydot
    c:\users\sd71ein\appdata\local\temp\mobaxterm7.1\tmp\pip_build_sd71ein\pydot\pydot.py:1: UserWarning: Couldn't import dot_parser, loading of dot files will not be possible.
      """Graphviz's dot language Python interface.
    C:\Program Files (x86)\IronPython 2.7\Lib\weakref.py:1: DeprecationWarning: object.__init__() takes no parameters for type KeyedRef
      """Weak reference support for Python.

Downloading/unpacking pyparsing>=2.1.4 (from pydot)
Installing collected packages: pydot, pyparsing
  Running setup.py install for pydot
    c:\users\sd71ein\appdata\local\temp\mobaxterm7.1\tmp\pip_build_sd71ein\pydot\pydot.py:1: UserWarning: Couldn't import dot_parser, loading of dot files will not be possible.
      """Graphviz's dot language Python interface.
    C:\Program Files (x86)\IronPython 2.7\Lib\weakref.py:1: DeprecationWarning: object.__init__() takes no parameters for type KeyedRef
      """Weak reference support for Python.
    warning: build_py: byte-compiling is disabled, skipping.

    warning: install_lib: byte-compiling is disabled, skipping.


C:\Program Files (x86)\IronPython 2.7\Lib\weakref.py:1: DeprecationWarning: object.__init__() takes no parameters for type KeyedRef
  """Weak reference support for Python.
Successfully installed pydot pyparsing
Cleaning up...
```

**Comment by Prodigio** [comment]
Has there been some progress? Having the same issue.
