### ISSUE TITLE
ImportError: cannot import name 'urlopen'

### ISSUE THREAD

**Issue by alexandnpu** [benjaminp/six#186]
```
Traceback (most recent call last):
  File "draw_plot.py", line 4, in <module>
    import matplotlib as plt
  File "/path/to/.alexpy3/lib/python3.6/site-packages/matplotlib/__init__.py", line 129, in <module>
    from six.moves.urllib.request import urlopen
ImportError: cannot import name 'urlopen'
```

My six version is 1.10.0

**Comment by alexandnpu** [comment]
After some trying, it came out that it is matplotlib that pollute my six environment.

as a matplotlib new comer, I did the following, which is wrong

```
import matplotlib as plt
```

this made the above import error. But I still can not find the root cause for this error.

When I use the following import as is written in the `matplotlib.__init__`.

```
import matplotlib.pyplot as plt
```
everything comes back.

I will open another issue for matplotlib for this, as this confuses not-so-careful beginners like me.
