### ISSUE TITLE
add_metaclass fails with name-mangled slots

### ISSUE THREAD

**Issue by alexpearce** [benjaminp/six#219]
The `add_metalclass` decorator assumes that [all members of `__slots__` will be exposed in the class `__dict__`](https://github.com/benjaminp/six/blob/63b2661b94463b59752396a3562c9e5ebe672f97/six.py#L844), but this isn't true for name-mangled slots (those having at least two leading underscores and at most one trailing underscore). Example:

```python
import six

class Meta(type):
    pass

@six.add_metaclass(Meta)
class Foo(object):
    __slots__ = (
        'something',
        '_something',
        '__something'
    )
```

Running this gives the error:

```
$ python bug.py
Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    class Foo(object):
  File "/home/apearce/tmp/six-bug/venv/lib/python3.6/site-packages/six.py", line 844, in wrapper
    orig_vars.pop(slots_var)
KeyError: '__something'
```

This is because the `__something` slot is given the key `_Foo__something` key in `__dict__`, not `__something`.

## Workarounds

Using `with_metaclass` works.

```python
import six

class Meta(type):
    pass

class Some(six.with_metaclass(Meta, object)):
    __slots__ = (
        'something',
        '_something',
        '__something'
    )
```

## Solutions

One way around this would be to detect if name mangling will happen.

```python
def _mangled_name(cls, name):
    """Return the mangled version of name belonging to cls, if appropriate.

    Python applies name mangling if the name starts with at least two
    underscores and ends with at most one underscore.
    """
    mangled = name.startswith('__') and not name.endswith('__')
    if mangled:
        name = '_{0}{1}'.format(cls.__name__, name)
    return name


def add_metaclass(metaclass):
    """Class decorator for creating a class with a metaclass."""
    def wrapper(cls):
        orig_vars = cls.__dict__.copy()
        slots = orig_vars.get('__slots__')
        if slots is not None:
            if isinstance(slots, str):
                slots = [slots]
            for slots_var in slots:
                orig_vars.pop(_mangled_name(cls, slots_var))
        orig_vars.pop('__dict__', None)
        orig_vars.pop('__weakref__', None)
        return metaclass(cls.__name__, cls.__bases__, orig_vars)
    return wrapper
```

I'd open an MR with this, but am not sure if this is the ideal solution.

**Comment by SimplyKnownAsG** [comment]
@benjaminp, after thinking about it further, I believe @alexpearce may be correct that using `with_metaclass` may be the best approach. Perhaps this could be resolved with a documentation change encouraging folks to use `with_metaclass` over the `add_metaclass` decorator.

Additional note, I think that `with_metaclass` could be also allow for bases not defined within the arguments of the function call by changing ~~`meta(name, bases, d)`~~ to `meta(name, bases + list(this_bases), d)`. I'm not sure that it is necessarily that beneficial.
