### ISSUE TITLE
six.reraise should not ignore exception type

### ISSUE THREAD

**Issue by cosven** [benjaminp/six#242]
As we can see, [six.reraise](https://github.com/benjaminp/six/blob/master/six.py#L693) just **ignore** the exception type in Python 3.
ps: it works correctly in Python 2.

For example::
```python
import sys
import six


class CustomException(Exception):
    pass


try:
    try:
        raise RuntimeError('hello world')
    except Exception as e:
        t, v, tb = sys.exc_info()

        six.reraise(CustomException, v, tb)
        #raise CustomException, v, tb  # Python 2
        #raise CustomException(e).with_traceback(tb)  # Python 3
except Exception as e:
    t, v, tb = sys.exc_info()  # t SHOULD be CustomException, but it is RuntimeError in Python 3
    raise
```

Python 2 output::
```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    six.reraise(CustomException, v, tb)
  File "/home/cosven/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "test.py", line 11, in <module>
    raise RuntimeError('hello world')
RuntimeError: hello world
```

Python 3 output::
```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    six.reraise(CustomException, v, tb)
  File "test.py", line 11, in <module>
    raise RuntimeError('hello world')
__main__.CustomException: hello world
```

**Comment by benjaminp** [comment]
As it's name suggests, `reraise` is for reraising an existing exception, possibly with a different traceback. Completely new exceptions are not its métier. I'm not sure what you expect to happen on Python2, since it has no concept of exception chaining.

**Comment by cosven** [comment]
> As it's name suggests, reraise is for reraising an existing exception, possibly with a different traceback. 

In my situation, I want to raise an existing exception with a different exception type and the same traceback. 

In Python 2, I do like this::
```
try:
     raise XXXException()
except Exception:
     t, v, tb = sys.exc_info()
     raise CustomException, v, tb
```

In Python 3, I can implement like this::
```
try:
     raise XXXException()
except Exception:
     t, v, tb = sys.exc_info()
     raise CustomException(v).with_traceback(tb)
```
I expect my codebase to be 2&3 compatible, I choose `six.reraise` to do such thing.


so, I modify the code to::
```
try:
     raise XXXException()
except Exception:
     t, v, tb = sys.exc_info()
     six.reraise(CustomException, v, tb)
```
> I'm not sure what you expect to happen on Python2, since it has no concept of exception chaining.

But the problem is that, as I stated above, `six.reraise` not working as expected (for me) in Python 3, but it works in Python 2. It raises a XXXException(original) in Python 3, and it raise a CustomException in Python 2. 

What I supposed `six.reraise` to raise is a `CustomException` instead of `XXXException` in both Python 2 and 3.

**Comment by wchill** [comment]
The proper usage here is probably

```
try:
     raise XXXException()
except Exception:
     t, v, tb = sys.exc_info()
     six.reraise(CustomException, CustomException(v), tb)
```

Only if v is None will it use CustomException, so you need to construct it yourself manually

https://github.com/benjaminp/six/blob/e114efceea962fb143c909c904157ca994246fd2/six.py#L687

**Comment by bertjwregeer** [comment]
It would be nice if this were documented in the documentation. `reraise` doesn't work the same across the two platforms in this case.
