### ISSUE TITLE
AttributeError: module 'six' has no attribute 'integer_types'

### ISSUE THREAD

**Issue by Pihu1998** [benjaminp/six#286]
> Traceback (most recent call last):
  File "C:\Users\PRANAMIKA\Nuitka\tests\standalone\six.dist\six.py", line 47, in <module>
  File "C:\Users\PRANAMIKA\Nuitka\tests\standalone\six.dist\six.py", line 29, in main
  File "C:\Users\PRANAMIKA\Nuitka\tests\standalone\six.dist\six.py", line 8, in dispatch_types
AttributeError: module 'six' has no attribute 'integer_types'

When running my code which uses `six.integer_types`, its showing an AttributeError. The Six version I am using is (1.12.0). The Python version I am using is Python 3.7. 
Please update the documentation for how to use it if in case it has to be for the new version of Python.

**Comment by benjaminp** [comment]
You are probably shadowing the `six` module with your own file called `six.py`.
