### ISSUE TITLE
add_metaclass: breaks super() without args

### ISSUE THREAD

**Issue by blueyed** [benjaminp/six#292]
Using the `six.add_metaclass` decorator breaks usage of `super()` without args in Python 3:

```python
import six

class Base():
    def method(self):
        print("Base.method")

class Meta(type):
    pass

# works:
# class C(Base, metaclass=Meta):
@six.add_metaclass(Meta)
class C(Base):
    def method(self):
        super().method()


C().method()
```

```
Traceback (most recent call last):
  File "t-six.py", line 18, in <module>
    C().method()
  File "t-six.py", line 15, in method
    super().method()
TypeError: super(type, obj): obj must be an instance or subtype of type
```

As a workaround `super(C, self)` can be used.

**Comment by blueyed** [comment]
I guess that's fair given that you have to use `super(C, self)` in the first place for compatibility though.. ;)
