### ISSUE TITLE
AttributeError: 'dictproxy' object has no attribute 'viewitems', 'viewvalues', 'viewkeys'

### ISSUE THREAD

**Issue by graingert** [benjaminp/six#295]
```
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> class Ham(object):
...     pass
... 
>>> import six
>>> six.viewitems(vars(Ham))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dictproxy' object has no attribute 'viewitems'
>>> six.viewvalues(vars(Ham))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dictproxy' object has no attribute 'viewvalues'
>>> six.viewkeys(vars(Ham))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dictproxy' object has no attribute 'viewkeys'
```

strictly speaking this might be a cPython bug, but I think the six methods need to include a check for dictproxy and handle this case

**Comment by graingert** [comment]
https://github.com/python/cpython/pull/15143

**Comment by graingert** [comment]
CPython will not be fixing this, so we need a workaround.

https://github.com/python/cpython/pull/15143#issuecomment-520376691
