### ISSUE TITLE
After upgrade from Django 2 to Django 3. I am getting this error. ImportError: cannot import name 'six' from 'django.utils'

### ISSUE THREAD

**Issue by AmitAps** [benjaminp/six#313]
python3 manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Aps/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/Aps/.local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/Aps/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/Aps/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/Aps/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/Aps/.local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/Aps/.local/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/Aps/.local/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/Aps/workspace/media_thesocialtalks/homee/thesocialtalks/news/models.py", line 5, in <module>
    from djrichtextfield.models import RichTextField
  File "/home/Aps/.local/lib/python3.7/site-packages/djrichtextfield/models.py", line 5, in <module>
    from djrichtextfield.sanitizer import SanitizerMixin
  File "/home/Aps/.local/lib/python3.7/site-packages/djrichtextfield/sanitizer.py", line 3, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/home/Aps/.local/lib/python3.7/site-packages/django/utils/__init__.py)

**Comment by NielkS** [comment]
Hi,
This is listed in the backward-incompatible changes of Django 3 - https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis
