### ISSUE TITLE
import docker python package thorws AttributeError: module 'six' has no attribute 'PY34'

### ISSUE THREAD

**Issue by manas86** [benjaminp/six#316]
As the subject line stated, I'm getting below error while I'm importing docker package in my python script. 
`Traceback (most recent call last):
  File "genericECR.py", line 1, in <module>
    import docker
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\docker\__init__.py", line 2, in <module>
    from .api import APIClient
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\docker\api\__init__.py", line 2, in <module>
    from .client import APIClient
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\docker\api\client.py", line 8, in <module>
    import websocket
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websocket\__init__.py", line 23, in <module>
    from ._app import WebSocketApp
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websocket\_app.py", line 36, in <module>
    from ._core import WebSocket, getdefaulttimeout
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websocket\_core.py", line 34, in <module>
    from ._handshake import *
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websocket\_handshake.py", line 40, in <module>
    if six.PY34:
AttributeError: module 'six' has no attribute 'PY34'`
my current python version in `3.8.0` 
and six is installed in my pc. 
`Requirement already satisfied: six in c:\users\appdata\local\programs\python\python38-32\lib\site-packages (1.6.1)`

it seems it's not compatible for python 3.8. So any advice ?

**Comment by manas86** [comment]
closing the issue, I had version 1.6.1 by upgrading to latest which is 1.13.0 fixed the issue.
