### ISSUE TITLE
ContextualVersionConflict on pytz while installing six 

### ISSUE THREAD

**Issue by rvacaru** [benjaminp/six#329]
During the installation of my python app `six 1.14.0` is also being installed. However the six installation fails because of a `ContextualVersionConflict` on the `pytz` library, here are the logs:

```
Searching for six
Reading https://pypi.org/simple/six/
Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl#sha256=8f3cd2e254d8f793e7f3d6d9df77b92252b52637291d0f0da013c76ea2724b6c
Best match: six 1.14.0
Processing six-1.14.0-py2.py3-none-any.whl
Installing six-1.14.0-py2.py3-none-any.whl to /home/vsts/work/1/s/.eggs

Installed /home/vsts/work/1/s/.eggs/six-1.14.0-py3.7.egg
Traceback (most recent call last):
  File "setup.py", line 52, in <module>
    url="https://github.com/godatadriven/predicting-demand",
  File "/home/vsts/.cache/pre-commit/repoytl0qf15/py_env-python3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/vsts/work/1/s/.eggs/pytest_runner-5.2-py3.7.egg/ptr.py", line 202, in run
    installed_dists = self.install_dists(dist)
  File "/home/vsts/work/1/s/.eggs/pytest_runner-5.2-py3.7.egg/ptr.py", line 153, in install_dists
    orig.test.install_dists(dist), self.install_extra_dists(dist)
  File "/home/vsts/.cache/pre-commit/repoytl0qf15/py_env-python3.7/lib/python3.7/site-packages/setuptools/command/test.py", line 209, in install_dists
    ir_d = dist.fetch_build_eggs(dist.install_requires)
  File "/home/vsts/.cache/pre-commit/repoytl0qf15/py_env-python3.7/lib/python3.7/site-packages/setuptools/dist.py", line 698, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/vsts/.cache/pre-commit/repoytl0qf15/py_env-python3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytz 2020.1 (/home/vsts/work/1/s/.eggs/pytz-2020.1-py3.7.egg), Requirement.parse('pytz<2020,>=2014.10'), {'convertdate'})


##[error]Bash exited with code '1'.
```

This seems to be related to an issue in pytz which has been resolved, but when limiting the pytz version it may occur: https://github.com/fitnr/convertdate/pull/27

Would you consider fixing this for six 1.14 as well?

**Comment by rvacaru** [comment]
Six is not even importing pytz, my bad :)
