### ISSUE TITLE
six.u mishandles string ending in backslash

### ISSUE THREAD

**Issue by benjaminp** [benjaminp/six#60]
Originally reported by: **Peter Bigot (Bitbucket: [pabigot](https://bitbucket.org/pabigot), GitHub: [pabigot](https://github.com/pabigot))**

----------------------------------------

It's an unusual case, perhaps, but for completeness:

```
Traceback (most recent call last):
  File "/tmp/x.py", line 21, in <module>
    x1 = six.u('\\')
  File "/opt/pyxb/pyxb/utils/six.py", line 515, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
UnicodeDecodeError: 'unicodeescape' codec can't decode byte 0x5c in position 0: \ at end of string
```

----------------------------------------
- Bitbucket: https://bitbucket.org/gutworth/six/issue/60

**Comment by benjaminp** [comment]
WONTFIXing

Use syntatic `u` prefix.
