### ISSUE TITLE
six tries to import inappropriate modules under certain circumstances

### ISSUE THREAD

**Issue by benjaminp** [benjaminp/six#87]
Originally reported by: **ceridwenv (Bitbucket: [ceridwenv](https://bitbucket.org/ceridwenv), GitHub: Unknown)**

----------------------------------------

I found this happening under unusual conditions, so I don't know how much of a general problem it is.  I'm trying to use [Pympler](https://pythonhosted.org/Pympler) to profile the memory used by a script that uses [Construct](http://construct.readthedocs.org/) for binary data parsing.  Construct imports six.  When trying to use a particular Pympler function, pympler.asizeof.asizeof(all = True), I get the following traceback:

```
#!python
Traceback (most recent call last):
  File "./dvilike.py", line 1150, in <module>
    print(pympler.asizeof.asizeof(all = True))
  File "/usr/local/lib/python3.4/dist-packages/pympler/asizeof.py", line 2086, in asizeof
    s = _asizer.asizeof(*t)
  File "/usr/local/lib/python3.4/dist-packages/pympler/asizeof.py", line 1681, in asizeof
    s, _ = self._sizes(objs, None)
  File "/usr/local/lib/python3.4/dist-packages/pympler/asizeof.py", line 1651, in _sizes
    s[i] = self._sizer(o, 0, sized)
  File "/usr/local/lib/python3.4/dist-packages/pympler/asizeof.py", line 1627, in _sizer
    s += z(o, d, None)
  File "/usr/local/lib/python3.4/dist-packages/pympler/asizeof.py", line 1627, in _sizer
    s += z(o, d, None)
  File "/usr/local/lib/python3.4/dist-packages/pympler/asizeof.py", line 1627, in _sizer
    s += z(o, d, None)
  File "/usr/local/lib/python3.4/dist-packages/pympler/asizeof.py", line 1627, in _sizer
    s += z(o, d, None)
  File "/usr/local/lib/python3.4/dist-packages/pympler/asizeof.py", line 1626, in _sizer
    for o in r(obj, False):
  File "/usr/local/lib/python3.4/dist-packages/pympler/asizeof.py", line 526, in _refs
    for _, o in _dir2(obj, **kwds):
  File "/usr/local/lib/python3.4/dist-packages/pympler/asizeof.py", line 370, in _dir2
    if hasattr(obj, slots):
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 109, in __getattr__
    _module = self._resolve()
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 106, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 77, in _import_module
    __import__(name)
ImportError: No module named 'winreg'
```
I'm on a Linux system, so of course there is no winreg module.

In trying to figure out what was happening with the debugger, I couldn't find any evidence that asizeof() was directly requesting the winreg import, so I suspect the problem is in six itself, but I don't understand what it's doing well enough to verify that.

----------------------------------------
- Bitbucket: https://bitbucket.org/gutworth/six/issue/87

**Comment by derekbelrose** [comment]
I'm seeing this as well when importing boto3 on pythonista.  I know it's been nearly 3 years since @benjaminp commented last, and I hate to necro this post, but is this still a problem for anyone else?

import boto3
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/FB154B72-0B7E-4803-A25A-82E79B42CCEB/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/six.py", line 127, in __getattr__
    _module = self._resolve()
  File "/var/containers/Bundle/Application/FB154B72-0B7E-4803-A25A-82E79B42CCEB/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/six.py", line 111, in _resolve
    return _import_module(self.mod)
  File "/var/containers/Bundle/Application/FB154B72-0B7E-4803-A25A-82E79B42CCEB/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/six.py", line 78, in _import_module
    __import__(name)
ModuleNotFoundError: No module named 'winreg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/mobile/Containers/Shared/AppGroup/9AD20990-8045-4AF3-9A60-0E6470679929/Pythonista3/Documents/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/private/var/mobile/Containers/Shared/AppGroup/9AD20990-8045-4AF3-9A60-0E6470679929/Pythonista3/Documents/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/private/var/mobile/Containers/Shared/AppGroup/9AD20990-8045-4AF3-9A60-0E6470679929/Pythonista3/Documents/site-packages/botocore/session.py", line 26, in <module>
    import botocore.credentials
  File "/private/var/mobile/Containers/Shared/AppGroup/9AD20990-8045-4AF3-9A60-0E6470679929/Pythonista3/Documents/site-packages/botocore/credentials.py", line 27, in <module>
    from dateutil.parser import parse
  File "/private/var/mobile/Containers/Shared/AppGroup/9AD20990-8045-4AF3-9A60-0E6470679929/Pythonista3/Documents/site-packages/dateutil/parser.py", line 17, in <module>
    from . import tz
  File "/private/var/mobile/Containers/Shared/AppGroup/9AD20990-8045-4AF3-9A60-0E6470679929/Pythonista3/Documents/site-packages/dateutil/tz.py", line 19, in <module>
    from dateutil.tzwin import tzwin, tzwinlocal
  File "/private/var/mobile/Containers/Shared/AppGroup/9AD20990-8045-4AF3-9A60-0E6470679929/Pythonista3/Documents/site-packages/dateutil/tzwin.py", line 26, in <module>
    TZKEYNAME = _settzkeyname()
  File "/private/var/mobile/Containers/Shared/AppGroup/9AD20990-8045-4AF3-9A60-0E6470679929/Pythonista3/Documents/site-packages/dateutil/tzwin.py", line 17, in _settzkeyname
    handle = winreg.ConnectRegistry(None, winreg.HKEY_LOCAL_MACHINE)
  File "/var/containers/Bundle/Application/FB154B72-0B7E-4803-A25A-82E79B42CCEB/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/six.py", line 129, in __getattr__
    raise AttributeError(attr)
AttributeError: ConnectRegistry
